export const GET_CONTACT_DATA = 'GET_CONTACT_DATA';
export const GET_CONTACT_DATA_SUCCESS = 'GET_CONTACT_DATA_SUCCESS';
export const GET_CONTACT_DATA_FAIL = 'GET_CONTACT_DATA_FAIL';
export const UPDATE_CONTACT_DATA = 'UPDATE_CONTACT_DATA';
